### ISSUE TITLE
REST Client Automatically Opens Every Single URL

### ISSUE THREAD

**Issue by Uri7337** [javierllorente/netbeans-rest-client#11]
Hi guys, 
it seems that i have downloaded netbeans 19 and somehow i have yours REST Client plugin. 

My problem is that every URL I click on is now opened in a REST client instead of a web browser. Can you help?

If it's unrelated to the plugin, please let me know, and i'll delete my Issue.
 
More Information about my problem:
[Here](https://stackoverflow.com/q/77236658/21454862?sem=2)

Thanks!
Have fun coding!

**Comment by javierllorente** [comment]
Hello!
Yes, it's a known issue. See #9
Greetings
