### ISSUE TITLE
JSON not highlighted anymore

### ISSUE THREAD

**Issue by Chris2011** [javierllorente/netbeans-rest-client#12]
When I GET a resource with a JSON response, the json is not highlighted anymore. When I look into your code, it is due to your changes of the mimetypes. NetBeans just knows the original mimetype application/json and not this "text/nbrc-content+json". What was the reason to change this?

I could fix this, but I would like to know the change to this mimetype. application/json is also coming from the resource, it is the content-type.

**Comment by javierllorente** [comment]
javadocs links were also opened by the REST Client instead of the Web browser. So I went the custom mime-type route to fix it. But it seems I have also added an unwanted extra "feature" :-(
See issue #9.

**Comment by Chris2011** [comment]
Ok understood, so you want to make links in your response in the body pane clickable and if they are clickable then the REST Client should open to make a new request?

**Comment by javierllorente** [comment]
It's already implemented. See commit b1ecbd9f9179ff7ad75bb89f05621d45b1cecf16

**Comment by Chris2011** [comment]
Ok but this was the initial idea. I just wanted to understand it first. Ok so lemme check the code, when I have time and let's find a solution. Maybe about parsing just the content of the editor pane or so.

**Comment by javierllorente** [comment]
Thanks!

**Comment by javierllorente** [comment]
Fixed by pull #15
