### ISSUE TITLE
SSL certificate verification

### ISSUE THREAD

**Issue by Sakhnovkrg** [javierllorente/netbeans-rest-client#4]
Please make it possible to disable SSL certificate verification

**Comment by javierllorente** [comment]
Are you having trouble with self-signed certificates?

**Comment by Sakhnovkrg** [comment]
yep

**Comment by javierllorente** [comment]
You can now enable/disable SSL certificate verification under Tools->Options->Miscellaneous->REST Client.
Shipped with v0.3.2
commit 8dbc569
