### ISSUE TITLE
Can't just use absolute URLs

### ISSUE THREAD

**Issue by Chris2011** [javierllorente/netbeans-rest-client#6]
This happens when I use google.de instead of https://google.de. It should also work w/o the protocol. Maybe we should add http in front of it in the background, if this is missing.

I also tried a URL which redirects from http to https and it shows me in the results panel HTML: "301 moved permanently" or for other URLs it shows me just the Status: 301 moved permanently. You can try out http://twitter.com.

Of course those are two different cases but the second case happens, when we automatically add http in front of it, also when we don't know which is the correct one.

So we should be aware of the redirect.

Example: google.de -> http://google.de -> https://google.de or twitter.com -> http://twitter.com -> https://twitter.com

So the end result in the response panel should be the real page at the end after all redirects. The browser also doesn't stop after the status from the Webserver, which would be weird.

**Comment by Chris2011** [comment]
The url which shows the 301 in response panel is puls-webagentur.de

**Comment by Chris2011** [comment]
The problem happens here: https://github.com/javierllorente/netbeans-rest-client/blob/main/src/main/java/com/javierllorente/netbeans/rest/client/ui/RestClientTopComponent.java#L271-L278

**Comment by javierllorente** [comment]
I am checking if the URL starts with http. If not, I prepend "http://" to it. 
I have also fixed the redirect issue by changing from the default Connector implementation to ApacheConnectorProvider. I hope there are no side effects.
Thanks for reporting it!
