### ISSUE TITLE
Format json (or another) response

### ISSUE THREAD

**Issue by ftoledo** [javierllorente/netbeans-rest-client#7]
hi! please optional formatter for results..
this api result a "one line" of json stanza

![imagen](https://user-images.githubusercontent.com/95441/234131838-ea2c0fb5-e76c-4494-b0f4-bfae4bd0d836.png)

i don't care for folding feature.. but fews line breaks just save muth time

Expected:
![imagen](https://user-images.githubusercontent.com/95441/234132232-c45e41e1-5143-4478-9f79-13efa78fd4a2.png)

**Comment by javierllorente** [comment]
I am working on it.
Thanks for your suggestion!

**Comment by javierllorente** [comment]
Feature implemented. Will be shipped in the next release.

**Comment by ftoledo** [comment]
Excelente! Muchas gracias!!!

**Comment by javierllorente** [comment]
De nada :wink:
