### ISSUE TITLE
Import and map postman exported data

### ISSUE THREAD

**Issue by Chris2011** [javierllorente/netbeans-rest-client#8]
I encountered, that I can export a collection with different requests from postman and it would be cool, if we can import it and use the same data from postman. Here is a demo file:

```json
{
	"info": {
		"_postman_id": "120d6e73-976e-44e9-9ebf-264f5d16ce96",
		"name": "Test",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "New Request",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "puls-webagentur.de",
					"host": [
						"puls-webagentur",
						"de"
					]
				}
			},
			"response": []
		}
	]
}
```

**Comment by Chris2011** [comment]
I would just say, take postman and play around. When I google for that I couldn't find that much except the json org scheme: https://schema.postman.com/collection/json/v2.0.0/draft-04/collection.json

**Comment by javierllorente** [comment]
I couldn't find much info either.
Thanks. I will take a look at it.

**Comment by javierllorente** [comment]
Sorry. I had forgotten about it.
I have just pushed an initial version. The import/export buttons can be found in the miscellaneous section; 
Tools → Options → Miscellaneous → REST Client
Only request method and URL can be imported/exported for now.
Commit db422d2

**Comment by javierllorente** [comment]
Headers can be now imported/exported.
Commit 1211ada

**Comment by javierllorente** [comment]
Closing this issue as it is now completed.

**Comment by Chris2011** [comment]
Awesome :)
