### ISSUE TITLE
REST Client hijacking JavaDoc calls

### ISSUE THREAD

**Issue by cbm64chris** [javierllorente/netbeans-rest-client#9]
Right clicking upon an artefact in the dependency tree a selecting Show JavaDoc displays the RESTClient rather than the selected browser of NetBeans. 

Probably best to add something to the config pane that allows a user to determine the default behaviour of when a URL is detected by the listener.

**Comment by javierllorente** [comment]
Thanks for reporting this bug. 
I'll see if I can make it non-IDE wide. Or at least let the user decide the behaviour.

**Comment by javierllorente** [comment]
Now only links of response to a REST Client request are opened by REST Client.

**Comment by cbm64chris** [comment]
Confirmed, built and installed in NetBeans 19 now has the desired behaviour. Nice work!

**Comment by javierllorente** [comment]
Thanks for testing it!
